presets:
  qwen:
    provider: qwen
    model: qwen-plus-2025-09-11
    base_url: https://dashscope.aliyuncs.com/compatible-mode/v1
    chat_completion_path: /chat/completions
    default_params:
      temperature: 0.7
  gemini:
    provider: gemini
    model: gemini-3.0-pro-preview
    base_url: https://generativelanguage.googleapis.com/v1beta
    chat_completion_path: /models/${model}:generateContent
    default_params:
      temperature: 0.7
